### ISSUE TITLE
[Phase 1] SCSS Styles

### ISSUE THREAD

**Issue by Antonytm** [exdst/Sitecore.Demo.XMCloud.Verticals#3]
Modify Astro build scripts to build existing *.scss files.

Astro layout should import `assets/main.scss` similar to `src/sxastarter/src/pages/_app.tsx`.
(_main.scss is built into CSS during Next.js build)

**Comment by Lawliet1701** [comment]
Downgraded Astro version to **5.0.0-beta.6** (temporarily) because **5.0.0-beta.7** has some problems with nested css imports.
